// Configuration for client-side
// This will be set by your deployment platform using environment variables

window.CONFIG = {
    // API endpoint - will be set by deployment platform
    API_BASE_URL: 'https://www.eyecareprovider.co.uk',
    
    // Stripe publishable key - will be injected by server
    STRIPE_PUBLISHABLE_KEY: 'pk_test_your_key_here'
};

// For production, this will be dynamically generated by your server
// or set via environment variables in your deployment platform